name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 监听的分支为 main，你可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # 确保使用的 Node.js 版本

    - name: Check commit message
      id: check_commit
      run: echo "contains_build=$(echo '${{ github.event.head_commit.message }}' | grep -qi 'build' && echo true || echo false)" >> $GITHUB_ENV

    - name: Install dependencies
      if: env.contains_build == 'true'
      run: npm install

    - name: Build project
      if: env.contains_build == 'true'
      run: npm run build

    - name: Deploy to GitHub Pages
      if: env.contains_build == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs # 修改为 docs 目录